name: Terraform Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install go
        go get -u github.com/gruntwork-io/terratest/modules/terraform

    - name: Run Terraform Tests
      working-directory: tests
      run: go test -v -timeout 30m

    - name: Terraform Init & Apply
      run: |
        terraform init
        terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
